<a href="https://colab.research.google.com/github/Atul57/Data-Science-project/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 = Create a 1D NumPy array of integers from 1 to 20 (inclusive) using np.arange().

In [ ]:
import numpy as np
array_1d = np.arange(1, 21)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q.2 = Create a 4×5 array of zeros. Then create another 4×5 array of ones. Add them together.

In [ ]:
zeros_array = np.zeros((4, 5))
print("Array of zeros (4x5):")
print(zeros_array)

Array of zeros (4x5):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
ones_array = np.ones((4, 5))
print("\nArray of ones (4x5):")
print(ones_array)


Array of ones (4x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
sum_array = zeros_array + ones_array
print("\nSum of the two arrays:")
print(sum_array)


Sum of the two arrays:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Q.3 = Create an array of 8 evenly spaced values between 0 and 1 using np.linspace(). Print the values

In [ ]:
import numpy as np
arr = np.linspace(0, 1, 8)
print(arr)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


Q.4 = Create np.arange(1, 25) and reshape it into a 4×6
array. Print the shape, number of dimensions
(ndim), and data type (dtype)

In [ ]:
import numpy as np

# Create array from 1 to 24 and reshape to 4x6
arr = np.arange(1, 25).reshape(4, 6)

# Print array
print("Array:")
print(arr)

# Print properties
print("\nShape:", arr.shape)
print("Number of dimensions (ndim):", arr.ndim)
print("Data type (dtype):", arr.dtype)

Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Shape: (4, 6)
Number of dimensions (ndim): 2
Data type (dtype): int64


Q. 5 = From the array [10, 20, 30, 40, 50, 60, 70, 80, 90,
100], extract: (a) first 5 elements, (b) last 3
elements, (c) every alternate element.

In [ ]:
import numpy as np

# Create the array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# (a) First 5 elements
first_5 = arr[:5]

# (b) Last 3 elements
last_3 = arr[-3:]

# (c) Every alternate element
alternate = arr[::2]

print("Original Array:", arr)
print("First 5 elements:", first_5)
print("Last 3 elements:", last_3)
print("Every alternate element:", alternate)

Original Array: [ 10  20  30  40  50  60  70  80  90 100]
First 5 elements: [10 20 30 40 50]
Last 3 elements: [ 80  90 100]
Every alternate element: [10 30 50 70 90]


Q. 6 = Create a 5×5 array using
np.arange(25).reshape(5,5). Extract: (a) row 2,
(b) column 3, (c) top-right 3×3 block.


In [ ]:
import numpy as np

# Create a 5×5 array
arr = np.arange(25).reshape(5, 5)

print("Original Array:")
print(arr)

# (a) Row 2 (3rd row, index 2)
row_2 = arr[2]

# (b) Column 3 (4th column, index 3)
col_3 = arr[:, 3]

# (c) Top-right 3×3 block
top_right = arr[:3, 2:]

print("\n(a) Row 2:")
print(row_2)

print("\n(b) Column 3:")
print(col_3)

print("\n(c) Top-right 3×3 block:")
print(top_right)

Original Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

(a) Row 2:
[10 11 12 13 14]

(b) Column 3:
[ 3  8 13 18 23]

(c) Top-right 3×3 block:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


Q . 7 = Create array a = [1, 2, 3, 4, 5]. Add 100 to every
element. Multiply every element by 3. Both
without any loop

In [ ]:
import numpy as np

# Create array
a = np.array([1, 2, 3, 4, 5])

# Add 100 to every element
add_100 = a + 100

# Multiply every element by 3
multiply_3 = a * 3

print("Original Array:", a)
print("After adding 100:", add_100)
print("After multiplying by 3:", multiply_3)

Original Array: [1 2 3 4 5]
After adding 100: [101 102 103 104 105]
After multiplying by 3: [ 3  6  9 12 15]


Q . 8 = Create two arrays: a = [10, 20, 30] and b = [1, 2,
3]. Compute: a+b, a-b, a*b, a/b element-wise

In [ ]:
import numpy as np

# Create arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Element-wise operations
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("a + b =", addition)
print("a - b =", subtraction)
print("a * b =", multiplication)
print("a / b =", division)

a + b = [11 22 33]
a - b = [ 9 18 27]
a * b = [10 40 90]
a / b = [10. 10. 10.]


Q . 9 = Given scores = [72, 85, 91, 68, 74, 88, 62, 95, 77,
80], compute: mean, median (np.median), std,
min, max, and range (max-min).

In [ ]:
import numpy as np

# Scores array
scores = np.array([72, 85, 91, 68, 74, 88, 62, 95, 77, 80])

# Statistics
mean = np.mean(scores)
median = np.median(scores)
std = np.std(scores)
minimum = np.min(scores)
maximum = np.max(scores)
range_val = maximum - minimum

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Range:", range_val)

Mean: 79.2
Median: 78.5
Standard Deviation: 10.02796090937734
Minimum: 62
Maximum: 95
Range: 33


Q . 10 = For a 3×4 random integer array
(np.random.randint(1,100,size=(3,4))): compute
sum across all elements, row-wise sum (axis=1),
and column-wise mean (axis=0).


In [ ]:
import numpy as np

# Create a 3×4 random integer array
arr = np.random.randint(1, 100, size=(3, 4))

print("Array:")
print(arr)

# Sum of all elements
total_sum = np.sum(arr)

# Row-wise sum
row_sum = np.sum(arr, axis=1)

# Column-wise mean
col_mean = np.mean(arr, axis=0)

print("\nSum of all elements:", total_sum)
print("Row-wise sum:", row_sum)
print("Column-wise mean:", col_mean)

Array:
[[79 13 39 85]
 [25 57 76 15]
 [54 79 31 12]]

Sum of all elements: 565
Row-wise sum: [216 173 176]
Column-wise mean: [52.66666667 49.66666667 48.66666667 37.33333333]


Generate 1000 random numbers from a normal
distribution (np.random.normal(mean=50,
std=10, size=1000)). Compute mean and std. Are
they close to 50 and 10?


In [ ]:
import numpy as np

# Generate 1000 random numbers
data = np.random.normal(loc=50, scale=10, size=1000)

# Compute mean and standard deviation
mean = np.mean(data)
std = np.std(data)

print("Mean:", mean)
print("Standard Deviation:", std)

Mean: 49.70520387207417
Standard Deviation: 10.291203313155583
